# Generated by Django 5.2.1 on 2025-05-30 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenserecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('TransactionType', models.CharField(max_length=8)),
                ('Category', models.CharField()),
                ('PaymentType', models.CharField()),
                ('Payedto', models.CharField()),
                ('FromWallet', models.CharField()),
                ('DateandTimePayed', models.DateTimeField()),
                ('Note', models.CharField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
