# Generated by Django 5.2.1 on 2025-06-07 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0003_wallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('category', models.CharField(choices=[('Food & Drinks', 'Food & Drinks'), ('Entertainment', 'Entertainment'), ('Groceries', 'Groceries'), ('Utilities', 'Utilities'), ('Transport', 'Transport'), ('Health', 'Health'), ('Other', 'Other')], max_length=20)),
                ('period', models.CharField(choices=[('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transactions.wallet')),
            ],
        ),
    ]
