# Generated by Django 5.2.1 on 2025-06-08 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0004_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='FromWallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transactions.wallet'),
        ),
    ]
