# Generated by Django 5.2.1 on 2025-06-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0005_alter_transactionrecord_fromwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='FromWallet',
            field=models.CharField(),
        ),
    ]
