# Generated by Django 5.2.1 on 2025-06-09 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0010_alter_transactionrecord_fromwallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Savings', 'Savings')], default='Primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'type')},
        ),
    ]
