# Generated by Django 5.2.1 on 2025-06-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0012_alter_budget_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='FromWallet',
            field=models.CharField(),
        ),
    ]
