# Generated by Django 5.2.1 on 2025-06-10 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0013_alter_transactionrecord_fromwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='FromWallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transactions.wallet'),
        ),
    ]
