# Generated by Django 5.2.1 on 2025-05-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenserecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('TransactionType', models.CharField(max_length=8)),
                ('Category', models.CharField()),
                ('PaymentType', models.CharField()),
                ('Payedto', models.CharField()),
                ('FromWallet', models.CharField()),
                ('DateandTimePayed', models.DateTimeField()),
            ],
        ),
    ]
