# Generated by Django 5.2.1 on 2025-05-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_usertoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
