# Generated by Django 5.2.1 on 2025-05-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_expenserecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='Note',
            field=models.CharField(null=True),
        ),
    ]
