# Generated by Django 5.1.6 on 2025-02-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_text', models.CharField(max_length=200)),
                ('expense_amount', models.IntegerField(verbose_name='Amount Spent')),
                ('expense_date', models.DateTimeField(verbose_name='Expense Date')),
            ],
        ),
    ]
